version: "3.9"
services:
  web:
    build: .
    ports:
      - "5002:5002"
    environment:
      - FLASK_DEBUG=development
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

